// <auto-generated />
using System;
using CodeEscape.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeEscape.Migrations
{
    [DbContext(typeof(CodeEscapeContext))]
    partial class CodeEscapeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeEscape.Models.Gamesession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnigmaAtual")
                        .HasColumnType("integer");

                    b.Property<bool>("Finalizada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("Pontuacao")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("gamesession", (string)null);
                });

            modelBuilder.Entity("CodeEscape.Models.Gamesessiondica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataUso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrdemEnigma")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("gamesessiondica", (string)null);
                });

            modelBuilder.Entity("CodeEscape.Models.TabelaDesafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dica")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("tabela_desafios", (string)null);
                });

            modelBuilder.Entity("CodeEscape.Models.TabelaRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CapaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CriadaEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CriadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAtiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.ToTable("tabela_room", (string)null);
                });

            modelBuilder.Entity("CodeEscape.Models.TabelaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("J");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tabela_usuario", (string)null);
                });

            modelBuilder.Entity("CodeEscape.Models.Gamesession", b =>
                {
                    b.HasOne("CodeEscape.Models.TabelaRoom", "Room")
                        .WithMany("Gamesessions")
                        .HasForeignKey("RoomId");

                    b.HasOne("CodeEscape.Models.TabelaUsuario", "User")
                        .WithMany("Gamesessions")
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeEscape.Models.Gamesessiondica", b =>
                {
                    b.HasOne("CodeEscape.Models.Gamesession", "GameSession")
                        .WithMany("Gamesessiondicas")
                        .HasForeignKey("GameSessionId")
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("CodeEscape.Models.TabelaDesafio", b =>
                {
                    b.HasOne("CodeEscape.Models.TabelaRoom", "Room")
                        .WithMany("TabelaDesafios")
                        .HasForeignKey("RoomId")
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CodeEscape.Models.TabelaRoom", b =>
                {
                    b.HasOne("CodeEscape.Models.TabelaUsuario", "Criador")
                        .WithMany("TabelaRooms")
                        .HasForeignKey("CriadorId")
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("CodeEscape.Models.Gamesession", b =>
                {
                    b.Navigation("Gamesessiondicas");
                });

            modelBuilder.Entity("CodeEscape.Models.TabelaRoom", b =>
                {
                    b.Navigation("Gamesessions");

                    b.Navigation("TabelaDesafios");
                });

            modelBuilder.Entity("CodeEscape.Models.TabelaUsuario", b =>
                {
                    b.Navigation("Gamesessions");

                    b.Navigation("TabelaRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
